version: '3'
services:
  fitfriends.frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitfriends.frontend.app
    restart: always
    ports:
      - 5173:5173
    networks:
      - fitfriends

networks:
  fitfriends:
    driver: bridge

volumes:
  fitfriends.frontend.volume:
