version: '3.9'
services:
  fitfriends.trainings.postgres:
    image: postgres:14-alpine
    container_name: fitfriends.trainings.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - fitfriends.postgres.trainings:/var/lib/postgresql/data

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d {POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - fitfriends.trainings

  fitfriends.trainings.pgadmin:
    image: dpage/pgadmin4
    container_name: fitfriends.trainings.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 8082:80
    depends_on:
      - fitfriends.trainings.postgres
    networks:
      - fitfriends.trainings

volumes:
  fitfriends.postgres.trainings:

networks:
  fitfriends.trainings:
    driver: bridge
